export const EGYPT_GOVERNORATES = [
  { id: "cairo", en: "Cairo", ar: "القاهرة" },
  { id: "alexandria", en: "Alexandria", ar: "الإسكندرية" },
  { id: "giza", en: "Giza", ar: "الجيزة" },
  { id: "dakahlia", en: "Dakahlia", ar: "الدقهلية" },
  { id: "red_sea", en: "Red Sea", ar: "البحر الأحمر" },
  { id: "beheira", en: "Beheira", ar: "البحيرة" },
  { id: "fayoum", en: "Fayoum", ar: "الفيوم" },
  { id: "gharbia", en: "Gharbia", ar: "الغربية" },
  { id: "ismailia", en: "Ismailia", ar: "الإسماعيلية" },
  { id: "menofia", en: "Menofia", ar: "المنوفية" },
  { id: "minya", en: "Minya", ar: "المنيا" },
  { id: "qalyubia", en: "Qalyubia", ar: "القليوبية" },
  { id: "new_valley", en: "New Valley", ar: "الوادي الجديد" },
  { id: "suez", en: "Suez", ar: "السويس" },
  { id: "aswan", en: "Aswan", ar: "أسوان" },
  { id: "assiut", en: "Assiut", ar: "أسيوط" },
  { id: "beni_suef", en: "Beni Suef", ar: "بني سويف" },
  { id: "port_said", en: "Port Said", ar: "بورسعيد" },
  { id: "damietta", en: "Damietta", ar: "دمياط" },
  { id: "sharkia", en: "Sharkia", ar: "الشرقية" },
  { id: "south_sinai", en: "South Sinai", ar: "جنوب سيناء" },
  { id: "kafr_el_sheikh", en: "Kafr El Sheikh", ar: "كفر الشيخ" },
  { id: "matrouh", en: "Matrouh", ar: "مطروح" },
  { id: "luxor", en: "Luxor", ar: "الأقصر" },
  { id: "qena", en: "Qena", ar: "قنا" },
  { id: "north_sinai", en: "North Sinai", ar: "شمال سيناء" },
  { id: "sohag", en: "Sohag", ar: "سوهاج" },
];
